### ISSUE TITLE
no grafana dashboard or data source by default

### ISSUE THREAD

**Issue by Dmitry1987** [solairerove/jmeter-grafana#2]
Hi, that's a nice package you created, and I tried to use it :+1:   
all works good and I'm able to connect to both grafana and influx from browser, but I can't setup the dashboard.  
as I understand, the "jmeter" database holds data, and exposed on 2003 as graphite.
so I tried first to add influxDB data source just to verify connection is ok:

![image](https://cloud.githubusercontent.com/assets/9369080/23102127/fe45f69e-f6ab-11e6-85be-8a209aa97b15.png)

and it works showing connection is possible between containers.  but the graphite  :2003  data source doesn't connect :(  
it gets stuck like this when I press "save and test":

![image](https://cloud.githubusercontent.com/assets/9369080/23102138/3a3075ee-f6ac-11e6-8658-d64344062f4c.png)

and manually running any SELECT or SHOW DATABASES from influx container always gets just hang:

```
[root@ip-172-31-13-202 ~]# docker exec 2bc9c8608cfd influx
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.13.0
InfluxDB shell version: 0.13.0
> SELECT * FROM "jmeter"

```

any advice how to connect the dashboards/data sources?  I've read through all conf and Dockerfiles in this repo but don't have idea why it is stuck... 

the "mvn verify"  jmeter runs good, DOSing tut.by with 16-20 req per second  lol :D   
maybe I need to modify the jmeter settings for this all to work?

thanks in advance :)

**Comment by Dmitry1987** [comment]
also, I imported the default jmeter dashboard - but I guess I need to use "graphite carbon metrics" that comes with this installation?

![image](https://cloud.githubusercontent.com/assets/9369080/23102167/d2e90bac-f6ac-11e6-9eed-20c081847574.png)

or this setup also should support the standard "Jmeter Load Test" dashboard from grafana repo?

**Comment by solairerove** [comment]
moment. i clone it and verify. it worked nicely, when i write it,

**Comment by solairerove** [comment]
### First of all let's see our users:
![image](https://cloud.githubusercontent.com/assets/9396988/23104288/d6545a9c-f6db-11e6-87f5-7ca0b27095cc.png)

___

### Then create one:
![image](https://cloud.githubusercontent.com/assets/9396988/23104291/e87eeaca-f6db-11e6-80c2-d9d62b010f85.png)

### See result:
![image](https://cloud.githubusercontent.com/assets/9396988/23104293/f61562a4-f6db-11e6-8f24-8b9147a928da.png)

___

### Here's data source settings with access label:
![image](https://cloud.githubusercontent.com/assets/9396988/23104301/1685c0ec-f6dc-11e6-9e0c-34dbc1fb7511.png)

___

### Influx card:
![image](https://cloud.githubusercontent.com/assets/9396988/23104305/28b31f4e-f6dc-11e6-90d9-61f6a3ec122e.png)

___

### I'd created new dashboard graph:
![image](https://cloud.githubusercontent.com/assets/9396988/23104320/88ac5f64-f6dc-11e6-83b0-27853795ce40.png)

___

### Start ЗАДУДОСИТЬ tests:
![image](https://cloud.githubusercontent.com/assets/9396988/23104329/b2cca574-f6dc-11e6-99a5-21c497835147.png)

___

### And here you are:
![image](https://cloud.githubusercontent.com/assets/9396988/23104330/b82a15f6-f6dc-11e6-8fec-27259fe176dd.png)

___

### P.S. You're welcome in this issue

**Comment by solairerove** [comment]
What i can advise you. Probably not using jmeter, cause we have such product as `Gatling` written on scala. Maybe there's some way to connect those results with grafana.
What about plugins? i'm not sure about installing on docker version.

**Comment by solairerove** [comment]
If you don't have any other questions, you may close the issue)

**Comment by Dmitry1987** [comment]
oh, I didn't create any user for influx, maybe by default it was with no users at all...

I tried the official grafana dashboard for jmeter,  but had to install influx + grafana manually on the host, not dockerized.  it works pretty well, here's some test i just did:

![image](https://cloud.githubusercontent.com/assets/9369080/23104845/ffb7cd0e-f6dd-11e6-9f4b-68f56f18b972.png)

![image](https://cloud.githubusercontent.com/assets/9369080/23104853/1710e0bc-f6de-11e6-9640-93239de1b017.png)


thanks for quick reply :)  
I hope this stack will be useful to others.  weird that nobody lands here from google as i did.  i'd expect plenty of people using such setup.

regarding gatling, i've seen the docs but as i have jmeter load tests already written - being lazy to rewrite them for gatling :)
